name = "nullpoga"
main = "src/index.ts"
compatibility_date = "2023-09-22"

kv_namespaces = [
  { binding = "ochinchinland", id = "3346c3ec6c9e4c4a99d3e47aee777ee7" },
  { binding = "nostr_relationship", id = "1552b3d9ec494e029ea605c9ef9da61e" }
]

[ai]
binding = "AI"
