name = "nullpoga"
main = "src/index.ts"
compatibility_date = "2023-09-22"

kv_namespaces = [
  { binding = "ochinchinland", id = "3346c3ec6c9e4c4a99d3e47aee777ee7" },
  { binding = "nostr_relationship", id = "1552b3d9ec494e029ea605c9ef9da61e" },
  { binding = "nostr_profile", id = "15418c1d70594a19ad7ca34f1f650ab5" }
]

[ai]
binding = "AI"

[[r2_buckets]]
binding = 'gyazo'
bucket_name = 'gyazo'
preview_bucket_name = 'gyazo'
